<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.samhsa.gov/ds4ppilot/contract/orchestrator"
	xmlns:di="http://www.samhsa.gov/ds4ppilot/schema/orchestrator"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	name="XDSDocumentService"
	targetNamespace="http://www.samhsa.gov/ds4ppilot/contract/orchestrator">
	<wsdl:types>
		<xsd:schema
			targetNamespace="http://www.samhsa.gov/ds4ppilot/schema/orchestrator" elementFormDefault="qualified" attributeFormDefault="unqualified">
			<xsd:element name="saveDocumentSetToXdsRepositoryRequest">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="documentSet" type="xsd:string"/>														
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>			
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="saveDocumentSetToXdsRepositoryRequest">
		<wsdl:part element="di:saveDocumentSetToXdsRepositoryRequest" name="parameters" />
	</wsdl:message>
	<wsdl:message name="saveDocumentSetToXdsRepositoryResponse">
		<wsdl:part name="return" type="xsd:boolean" />
	</wsdl:message>
	<wsdl:portType name="XDSDocumentServicePortType">
		<wsdl:operation name="saveDocumentSetToXdsRepository">
			<wsdl:documentation>Store any clinical document set to XDS Repository
			</wsdl:documentation>
			<wsdl:input message="tns:saveDocumentSetToXdsRepositoryRequest" />
			<wsdl:output message="tns:saveDocumentSetToXdsRepositoryResponse" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="XDSDocumentServiceBinding"
		type="tns:XDSDocumentServicePortType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="saveDocumentSetToXdsRepository">
			<soap:operation soapAction="" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="XDSDocumentService">
		<wsdl:port binding="tns:XDSDocumentServiceBinding"
			name="XDSDocumentServicePort">
			<soap:address
				location="http://localhost:90/Orchestrator/services/xdsdocumentservice" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
