/*******************************************************************************
 * Copyright 2012 SAMHSA
 * 
 * Licensed under the Substance Abuse & Mental Health Services Administration (SAMHSA), you may not use this file except in compliance with the License.
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package gov.samhsa.ds4ppilot.contract.healthcareclassificationservice.client;

import gov.samhsa.ds4ppilot.contract.healthcareclassificationservice.HealthcareClassificationServicePortType;
import gov.samhsa.ds4ppilot.schema.healthcareclassificationservice.AssertAndExecuteClinicalFactsRequest;
import gov.samhsa.ds4ppilot.schema.healthcareclassificationservice.AssertAndExecuteClinicalFactsResponse;

import java.util.logging.Logger;

// TODO: Auto-generated Javadoc
/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-10-04T16:12:26.076-04:00
 * Generated source version: 2.6.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "HealthcareClassificationService",
                      portName = "HealthcareClassificationServicePort",
                      targetNamespace = "http://www.samhsa.gov/ds4ppilot/contract/HealthcareClassificationService",
                      wsdlLocation = "classpath:HealthcareClassificationService.wsdl",
                      endpointInterface = "gov.samhsa.ds4ppilot.contract.healthcareclassificationservice.HealthcareClassificationServicePortType")
                      
public class HealthcareClassificationServicePortTypeImpl implements HealthcareClassificationServicePortType {

    /** The Constant LOG. */
    private static final Logger LOG = Logger.getLogger(HealthcareClassificationServicePortTypeImpl.class.getName());
    
    /** The returned value of assert and execute clinical facts. */
    protected static AssertAndExecuteClinicalFactsResponse returnedValueOfAssertAndExecuteClinicalFacts;

    /* (non-Javadoc)
     * @see gov.samhsa.ds4ppilot.contract.healthcareclassificationservice.HealthcareClassificationServicePortType#assertAndExecuteClinicalFacts(gov.samhsa.ds4ppilot.schema.healthcareclassificationservice.AssertAndExecuteClinicalFactsRequest  parameters )*
     */
    /**
     * Assert and execute clinical facts.
     *
     * @param parameters the parameters
     * @return the assert and execute clinical facts response
     */
    @Override
	public AssertAndExecuteClinicalFactsResponse assertAndExecuteClinicalFacts(AssertAndExecuteClinicalFactsRequest parameters) { 
        LOG.info("Executing operation assertAndExecuteClinicalFacts");
        System.out.println(parameters);
        try {
            return returnedValueOfAssertAndExecuteClinicalFacts;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
