/*******************************************************************************
 * Open Behavioral Health Information Technology Architecture (OBHITA.org)
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the <organization> nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package gov.va.ehtac.ds4p.ws.client;

import gov.va.ehtac.ds4p.ws.Clinicaltagrule;
import gov.va.ehtac.ds4p.ws.DS4PClinicallyAdaptiveRulesInterface;
import gov.va.ehtac.ds4p.ws.OrganizationalPolicy;

import java.util.List;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-09-24T11:31:48.353-04:00
 * Generated source version: 2.6.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "DS4PClinicallyAdaptiveRulesInterface",
                      portName = "DS4PClinicallyAdaptiveRulesInterfacePort",
                      targetNamespace = "http://ws.ds4p.ehtac.va.gov/",
                      wsdlLocation = "classpath:DS4PClinicallyAdaptiveRulesInterface.wsdl",
                      endpointInterface = "gov.va.ehtac.ds4p.ws.DS4PClinicallyAdaptiveRulesInterface")
                      
public class DS4PClinicallyAdaptiveRulesInterfaceImpl implements DS4PClinicallyAdaptiveRulesInterface {

    private static final Logger LOG = Logger.getLogger(DS4PClinicallyAdaptiveRulesInterfaceImpl.class.getName());
    
    protected static List<OrganizationalPolicy> returnedValueOfGetAllOrganizationalPolicy;
    protected static Boolean returnedValueOfSetClinicalDomainTaggingRule;
    protected static String returnedValueOfGetCASRuleSetStringByPOUObligationsAndHomeCommunityId;
    protected static Clinicaltagrule returnedValueOfGetClinicalDomainRule;
    protected static Boolean returnedValueOfSetOrganizationalPolicy;
    protected static OrganizationalPolicy returnedValueOfGetOrganizationalPolicy;

    /* (non-Javadoc)
     * @see gov.va.ehtac.ds4p.ws.DS4PClinicallyAdaptiveRulesInterface#getAllOrganizationalPolicy(*
     */
    @Override
	public List<OrganizationalPolicy> getAllOrganizationalPolicy() { 
        LOG.info("Executing operation getAllOrganizationalPolicy");
        try {
            return returnedValueOfGetAllOrganizationalPolicy;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gov.va.ehtac.ds4p.ws.DS4PClinicallyAdaptiveRulesInterface#setClinicalDomainTaggingRule(gov.va.ehtac.ds4p.ws.Clinicaltagrule  taggingRule )*
     */
    @Override
	public Boolean setClinicalDomainTaggingRule(Clinicaltagrule taggingRule) { 
        LOG.info("Executing operation setClinicalDomainTaggingRule");
        System.out.println(taggingRule);
        try {
            return returnedValueOfSetClinicalDomainTaggingRule;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gov.va.ehtac.ds4p.ws.DS4PClinicallyAdaptiveRulesInterface#getCASRuleSetStringByPOUObligationsAndHomeCommunityId(java.lang.String  pou ,)java.util.List<java.lang.String>  obligations ,)java.lang.String  homeCommunityId ,)java.lang.String  messageId )*
     */
    @Override
	public String getCASRuleSetStringByPOUObligationsAndHomeCommunityId(String pou, List<String> obligations, String homeCommunityId, String messageId) { 
        LOG.info("Executing operation getCASRuleSetStringByPOUObligationsAndHomeCommunityId");
        System.out.println(pou);
        System.out.println(obligations);
        System.out.println(homeCommunityId);
        System.out.println(messageId);
        try {
            return returnedValueOfGetCASRuleSetStringByPOUObligationsAndHomeCommunityId;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gov.va.ehtac.ds4p.ws.DS4PClinicallyAdaptiveRulesInterface#getClinicalDomainRule(java.lang.String  domainLoincCode )*
     */
    @Override
	public Clinicaltagrule getClinicalDomainRule(String domainLoincCode) { 
        LOG.info("Executing operation getClinicalDomainRule");
        System.out.println(domainLoincCode);
        try {
            return returnedValueOfGetClinicalDomainRule;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gov.va.ehtac.ds4p.ws.DS4PClinicallyAdaptiveRulesInterface#setOrganizationalPolicy(gov.va.ehtac.ds4p.ws.OrganizationalPolicy  policy )*
     */
    @Override
	public Boolean setOrganizationalPolicy(OrganizationalPolicy policy) { 
        LOG.info("Executing operation setOrganizationalPolicy");
        System.out.println(policy);
        try {
            return returnedValueOfSetOrganizationalPolicy;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gov.va.ehtac.ds4p.ws.DS4PClinicallyAdaptiveRulesInterface#getOrganizationalPolicy(java.lang.String  homeCommunityId )*
     */
    @Override
	public OrganizationalPolicy getOrganizationalPolicy(String homeCommunityId) { 
        LOG.info("Executing operation getOrganizationalPolicy");
        System.out.println(homeCommunityId);
        try {
            return returnedValueOfGetOrganizationalPolicy;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
