/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package gov.samhsa.ds4ppilot.ws.client;

import ihe.iti.xds_b._2007.ProvideAndRegisterDocumentSetRequest;
import ihe.iti.xds_b._2007.RetrieveDocumentSetRequest;
import ihe.iti.xds_b._2007.RetrieveDocumentSetResponse;
import ihe.iti.xds_b._2007.XDSRepository;

import java.util.logging.Logger;

import oasis.names.tc.ebxml_regrep.xsd.rs._3.RegistryResponse;

// TODO: Auto-generated Javadoc
/**
 * This class was generated by Apache CXF 2.6.0 2012-11-18T23:54:47.950-05:00
 * Generated source version: 2.6.0
 * 
 */

@javax.jws.WebService(serviceName = "DocumentRepositoryService", portName = "XDSRepository_HTTP_Endpoint", targetNamespace = "http://tempuri.org/", wsdlLocation = "classpath:XDS.b_repository.net.wsdl", endpointInterface = "ihe.iti.xds_b._2007.XDSRepository")
public class XdsRepositorybImpl implements XDSRepository {

	/** The Constant LOG. */
	private static final Logger LOG = Logger.getLogger(XdsRepositorybImpl.class
			.getName());
	
	/** The returned value of retrieve document set. */
	protected static ihe.iti.xds_b._2007.RetrieveDocumentSetResponse returnedValueOfRetrieveDocumentSet;
	
	/** The returned value of provide and register document set. */
	protected static RegistryResponse returnedValueOfProvideAndRegisterDocumentSet;

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * ihe.iti.xds_b._2007.XDSRepository#retrieveDocumentSet(ihe.iti.xds_b._2007
	 * .RetrieveDocumentSetRequest input )*
	 */
	/**
	 * Retrieve document set.
	 *
	 * @param input the input
	 * @return the ihe.iti.xds_b._2007. retrieve document set response
	 */
	@Override
	public ihe.iti.xds_b._2007.RetrieveDocumentSetResponse retrieveDocumentSet(
			RetrieveDocumentSetRequest input) {
		LOG.info("Executing operation retrieveDocumentSet");
		System.out.println(input);
		try {
			returnedValueOfRetrieveDocumentSet = new RetrieveDocumentSetResponse();
			return returnedValueOfRetrieveDocumentSet;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * ihe.iti.xds_b._2007.XDSRepository#provideAndRegisterDocumentSet(ihe.iti
	 * .xds_b._2007.ProvideAndRegisterDocumentSetRequest input )*
	 */
	/**
	 * Provide and register document set.
	 *
	 * @param input the input
	 * @return the registry response
	 */
	@Override
	public RegistryResponse provideAndRegisterDocumentSet(
			ProvideAndRegisterDocumentSetRequest input) {
		LOG.info("Executing operation provideAndRegisterDocumentSet");
		System.out.println(input);
		try {
			returnedValueOfProvideAndRegisterDocumentSet = new RegistryResponse();
			return returnedValueOfProvideAndRegisterDocumentSet;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
