
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package gov.samhsa.ds4ppilot.ws.client;

import ihe.iti.xds_b._2007.ProvideAndRegisterDocumentSetRequest;
import ihe.iti.xds_b._2007.RetrieveDocumentSetRequest;
import ihe.iti.xds_b._2007.RetrieveDocumentSetResponse;
import ihe.iti.xds_b._2007.XDSRepository;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-11-18T23:54:47.950-05:00
 * Generated source version: 2.6.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "DocumentRepositoryService",
                      portName = "XDSRepository_HTTP_Endpoint",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "classpath:XDS.b_repository.net.wsdl",
                      endpointInterface = "ihe.iti.xds_b._2007.XDSRepository")
                      
public class XdsRepositorybImpl implements XDSRepository {

    private static final Logger LOG = Logger.getLogger(XdsRepositorybImpl.class.getName());
    protected static ihe.iti.xds_b._2007.RetrieveDocumentSetResponse returnedValueOfRetrieveDocumentSet;
    
    /* (non-Javadoc)
     * @see ihe.iti.xds_b._2007.XDSRepository#retrieveDocumentSet(ihe.iti.xds_b._2007.RetrieveDocumentSetRequest  input )*
     */
    public ihe.iti.xds_b._2007.RetrieveDocumentSetResponse retrieveDocumentSet(RetrieveDocumentSetRequest input) { 
        LOG.info("Executing operation retrieveDocumentSet");
        System.out.println(input);
        try {
        	 returnedValueOfRetrieveDocumentSet =  new RetrieveDocumentSetResponse();        
            return returnedValueOfRetrieveDocumentSet;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ihe.iti.xds_b._2007.XDSRepository#provideAndRegisterDocumentSet(ihe.iti.xds_b._2007.ProvideAndRegisterDocumentSetRequest  input )*
     */
    public ihe.iti.xds_b._2007.ProvideAndRegisterDocumentSetResponse provideAndRegisterDocumentSet(ProvideAndRegisterDocumentSetRequest input) { 
        LOG.info("Executing operation provideAndRegisterDocumentSet");
        System.out.println(input);
        try {
            ihe.iti.xds_b._2007.ProvideAndRegisterDocumentSetResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
