package gov.samhsa.ds4ppilot.ws.client;

import ihe.iti.xds_b._2007.XDSRegistry;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

import com.microsoft.schemas.message.RegistryStoredQueryResult;

/**
 * This class was generated by Apache CXF 2.6.0 2012-11-21T08:25:58.844-05:00
 * Generated source version: 2.6.0
 * 
 */

@WebService(serviceName = "DocumentRegistryService", portName = "XDSRegistry_HTTP_Endpoint", targetNamespace = "http://tempuri.org/", wsdlLocation = "classpath:XDS.b_registry.net.wsdl", endpointInterface = "ihe.iti.xds_b._2007.XDSRegistry")
public class XdsbRegistryServiceImpl implements XDSRegistry {

	private static final Logger LOG = Logger.getLogger(XdsbRegistryServiceImpl.class
			.getName());
	
	protected  static RegistryStoredQueryResult returnedValueOfRegistryStoredQuery;

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * ihe.iti.xds_b._2007.XDSRegistry#patientRegistryRecordRevised(com.microsoft
	 * .schemas.message.MessageBody input )*
	 */
	public com.microsoft.schemas.message.MessageBody patientRegistryRecordRevised(
			com.microsoft.schemas.message.MessageBody input) {
		LOG.info("Executing operation patientRegistryRecordRevised");
		System.out.println(input);
		try {
			com.microsoft.schemas.message.MessageBody _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * ihe.iti.xds_b._2007.XDSRegistry#updateDocumentSet(com.microsoft.schemas
	 * .message.MessageBody input )*
	 */
	public com.microsoft.schemas.message.MessageBody updateDocumentSet(
			com.microsoft.schemas.message.MessageBody input) {
		LOG.info("Executing operation updateDocumentSet");
		System.out.println(input);
		try {
			com.microsoft.schemas.message.MessageBody _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see ihe.iti.xds_b._2007.XDSRegistry#registryStoredQuery(oasis.names.tc.
	 * ebxml_regrep.xsd.query._3.AdhocQueryRequest input )*
	 */
	public com.microsoft.schemas.message.RegistryStoredQueryResult registryStoredQuery(
			oasis.names.tc.ebxml_regrep.xsd.query._3.AdhocQueryRequest input) {
		LOG.info("Executing operation registryStoredQuery");
		System.out.println(input);
		try {
			com.microsoft.schemas.message.RegistryStoredQueryResult _return = returnedValueOfRegistryStoredQuery;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * ihe.iti.xds_b._2007.XDSRegistry#deleteDocumentSet(com.microsoft.schemas
	 * .message.MessageBody input )*
	 */
	public com.microsoft.schemas.message.MessageBody deleteDocumentSet(
			com.microsoft.schemas.message.MessageBody input) {
		LOG.info("Executing operation deleteDocumentSet");
		System.out.println(input);
		try {
			com.microsoft.schemas.message.MessageBody _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * ihe.iti.xds_b._2007.XDSRegistry#patientRegistryRecordAdded(com.microsoft
	 * .schemas.message.MessageBody input )*
	 */
	public com.microsoft.schemas.message.MessageBody patientRegistryRecordAdded(
			com.microsoft.schemas.message.MessageBody input) {
		LOG.info("Executing operation patientRegistryRecordAdded");
		System.out.println(input);
		try {
			com.microsoft.schemas.message.MessageBody _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * ihe.iti.xds_b._2007.XDSRegistry#patientRegistryDuplicatesResolved(com
	 * .microsoft.schemas.message.MessageBody input )*
	 */
	public com.microsoft.schemas.message.MessageBody patientRegistryDuplicatesResolved(
			com.microsoft.schemas.message.MessageBody input) {
		LOG.info("Executing operation patientRegistryDuplicatesResolved");
		System.out.println(input);
		try {
			com.microsoft.schemas.message.MessageBody _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * ihe.iti.xds_b._2007.XDSRegistry#registerDocumentSet(com.microsoft.schemas
	 * .message.MessageBody input )*
	 */
	public com.microsoft.schemas.message.MessageBody registerDocumentSet(
			com.microsoft.schemas.message.MessageBody input) {
		LOG.info("Executing operation registerDocumentSet");
		System.out.println(input);
		try {
			com.microsoft.schemas.message.MessageBody _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}